# @docker-compose docker-compose.dev.yml
# @purpose Development environment with volume mounting and hot reload
# @compose_type development
# @services [  backend,   frontend,   nonprofit-network]
# @networks [  nonprofit-network]
# @layer infrastructure
# @llm-read true
# @llm-write full-edit
# @llm-role orchestration

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nonprofit-calculator-backend-dev
    ports:
      - "5000:5000"
    environment:
      - DEBUG=True
      - PORT=5000
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/venv
    command: python app.py
    networks:
      - nonprofit-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: nonprofit-calculator-frontend-dev
    ports:
      - "8080:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - nonprofit-network

networks:
  nonprofit-network:
    driver: bridge
